services:
  - type: web
    name: andrews-travellers-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20

  - type: static
    name: andrews-travellers-pwa
    env: static
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist/frontend/browser
    envVars:
      - key: NODE_VERSION
        value: 20

databases:
  - name: andrews-travellers-db
    plan: free
